name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04  # نسخة ثابتة ومستقرة
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSerebrenninkov/buildozer-action@v1.6.1
        with:
          command: android debug
          buildozer_version: master
          
