name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}-${{ steps.get-date.outputs.date }}

      - name: Build with Buildozer
        # هادي هي النسخة الرسمية والمستقرة 100%
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer_version: master
          command: android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tayeb-Link-Final
          path: bin/*
          .apk
