name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Buildozer Action
        uses: jreleaser/buildozer-action@v1
        with:
          command: android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tayeb-Link-Final
          path: bin/*.apk
          
